### ISSUE TITLE
Iframe (site refuses to connect)

### ISSUE THREAD

**Issue by FrancSimari** [DNNCommunity/DNN.IFrame#17]
## Describe the bug
Refuses to connect
## To Reproduce
Go through settings, indicate url and dimensions save site refuses to connect.
replaced original URL with Google.com and also refuses to connect
Tried another site worked but auto vertical sizing did not work. 
the above was using new install dnn v9.02 however, all of the above worked fine on dnn v8.0.4
iframe version 8.1.1

No event errors

**Comment by MaiklT** [comment]
The most possible reason for this is that the site you want to load cannot be loaded inside a frame or iframe because the owner of the site has set a header to avoid clickjacking. In Internet Explorer and Edge there is a message telling you that the page cannot be displayed within a frame, and a link to open the page in a new window. In Firefox it just remains white. For more information see [https://de.wikipedia.org/wiki/Clickjacking](https://de.wikipedia.org/wiki/Clickjacking) and [https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options](https://developer.mozilla.org/de/docs/Web/HTTP/Headers/X-Frame-Options).
So this is not a bug, and nothing we can do against it. It is a decision of the web site's owner.

To make the autosize feature work you need a piece of JavaScript on the other page (the one that you want to get displayed inside the IFrame). Also here, you do not have too much incluence if this is not your site.
